# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import secure_service_pb2 as secure__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in secure_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SecureServiceStub(object):
    """SecureService - storitev z vzajemno avtentikacijo (mTLS)
    Identiteta klienta je zaščitena s šifriranjem na transportni plasti
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/secure_service.SecureService/SendMessage',
                request_serializer=secure__service__pb2.MessageRequest.SerializeToString,
                response_deserializer=secure__service__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.GetServerInfo = channel.unary_unary(
                '/secure_service.SecureService/GetServerInfo',
                request_serializer=secure__service__pb2.ServerInfoRequest.SerializeToString,
                response_deserializer=secure__service__pb2.ServerInfoResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/secure_service.SecureService/Ping',
                request_serializer=secure__service__pb2.PingRequest.SerializeToString,
                response_deserializer=secure__service__pb2.PingResponse.FromString,
                _registered_method=True)


class SecureServiceServicer(object):
    """SecureService - storitev z vzajemno avtentikacijo (mTLS)
    Identiteta klienta je zaščitena s šifriranjem na transportni plasti
    """

    def SendMessage(self, request, context):
        """Pošlje šifrirano sporočilo strežniku
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerInfo(self, request, context):
        """Pridobi informacije o strežniku (preveri identiteto strežnika)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Ping - test vzpostavljene varne seje
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=secure__service__pb2.MessageRequest.FromString,
                    response_serializer=secure__service__pb2.MessageResponse.SerializeToString,
            ),
            'GetServerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerInfo,
                    request_deserializer=secure__service__pb2.ServerInfoRequest.FromString,
                    response_serializer=secure__service__pb2.ServerInfoResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=secure__service__pb2.PingRequest.FromString,
                    response_serializer=secure__service__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'secure_service.SecureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('secure_service.SecureService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SecureService(object):
    """SecureService - storitev z vzajemno avtentikacijo (mTLS)
    Identiteta klienta je zaščitena s šifriranjem na transportni plasti
    """

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/secure_service.SecureService/SendMessage',
            secure__service__pb2.MessageRequest.SerializeToString,
            secure__service__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/secure_service.SecureService/GetServerInfo',
            secure__service__pb2.ServerInfoRequest.SerializeToString,
            secure__service__pb2.ServerInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/secure_service.SecureService/Ping',
            secure__service__pb2.PingRequest.SerializeToString,
            secure__service__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
