# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: secure_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'secure_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14secure_service.proto\x12\x0esecure_service\"H\n\x0eMessageRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\t\"a\n\x0fMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x18\n\x10server_timestamp\x18\x03 \x01(\t\x12\x12\n\nsession_id\x18\x04 \x01(\t\"\'\n\x11ServerInfoRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"u\n\x12ServerInfoResponse\x12\x13\n\x0bserver_name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x1f\n\x17\x63\x65rtificate_fingerprint\x18\x03 \x01(\t\x12\x18\n\x10supported_cipher\x18\x04 \x01(\t\"#\n\x0bPingRequest\x12\x14\n\x0c\x63lient_nonce\x18\x01 \x01(\t\"M\n\x0cPingResponse\x12\x14\n\x0cserver_nonce\x18\x01 \x01(\t\x12\x14\n\x0c\x63lient_nonce\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t2\xfa\x01\n\rSecureService\x12N\n\x0bSendMessage\x12\x1e.secure_service.MessageRequest\x1a\x1f.secure_service.MessageResponse\x12V\n\rGetServerInfo\x12!.secure_service.ServerInfoRequest\x1a\".secure_service.ServerInfoResponse\x12\x41\n\x04Ping\x12\x1b.secure_service.PingRequest\x1a\x1c.secure_service.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secure_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=40
  _globals['_MESSAGEREQUEST']._serialized_end=112
  _globals['_MESSAGERESPONSE']._serialized_start=114
  _globals['_MESSAGERESPONSE']._serialized_end=211
  _globals['_SERVERINFOREQUEST']._serialized_start=213
  _globals['_SERVERINFOREQUEST']._serialized_end=252
  _globals['_SERVERINFORESPONSE']._serialized_start=254
  _globals['_SERVERINFORESPONSE']._serialized_end=371
  _globals['_PINGREQUEST']._serialized_start=373
  _globals['_PINGREQUEST']._serialized_end=408
  _globals['_PINGRESPONSE']._serialized_start=410
  _globals['_PINGRESPONSE']._serialized_end=487
  _globals['_SECURESERVICE']._serialized_start=490
  _globals['_SECURESERVICE']._serialized_end=740
# @@protoc_insertion_point(module_scope)
