# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import naloga2_pb2 as naloga2__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in naloga2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Naloga2Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendOne = channel.unary_unary(
                '/Naloga2/SendOne',
                request_serializer=naloga2__pb2.Stevilo.SerializeToString,
                response_deserializer=naloga2__pb2.Empty.FromString,
                _registered_method=True)
        self.GetOne = channel.unary_unary(
                '/Naloga2/GetOne',
                request_serializer=naloga2__pb2.Indeks.SerializeToString,
                response_deserializer=naloga2__pb2.Stevilo.FromString,
                _registered_method=True)
        self.SendMore = channel.stream_unary(
                '/Naloga2/SendMore',
                request_serializer=naloga2__pb2.Stevilo.SerializeToString,
                response_deserializer=naloga2__pb2.Empty.FromString,
                _registered_method=True)
        self.GetAll = channel.unary_stream(
                '/Naloga2/GetAll',
                request_serializer=naloga2__pb2.Empty.SerializeToString,
                response_deserializer=naloga2__pb2.Stevilo.FromString,
                _registered_method=True)


class Naloga2Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendOne(self, request, context):
        """1. Pošlji eno število → strežnik shrani, vrne Empty
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOne(self, request, context):
        """2. Pošlji indeks → strežnik vrne število na tistem mestu v seznamu
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMore(self, request_iterator, context):
        """3. Pošlji stream števil → strežnik shrani vsa, vrne Empty
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAll(self, request, context):
        """4. Pošlji Empty → strežnik vrne stream vseh shranjenih števil
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Naloga2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendOne': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOne,
                    request_deserializer=naloga2__pb2.Stevilo.FromString,
                    response_serializer=naloga2__pb2.Empty.SerializeToString,
            ),
            'GetOne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOne,
                    request_deserializer=naloga2__pb2.Indeks.FromString,
                    response_serializer=naloga2__pb2.Stevilo.SerializeToString,
            ),
            'SendMore': grpc.stream_unary_rpc_method_handler(
                    servicer.SendMore,
                    request_deserializer=naloga2__pb2.Stevilo.FromString,
                    response_serializer=naloga2__pb2.Empty.SerializeToString,
            ),
            'GetAll': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=naloga2__pb2.Empty.FromString,
                    response_serializer=naloga2__pb2.Stevilo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Naloga2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Naloga2', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Naloga2(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Naloga2/SendOne',
            naloga2__pb2.Stevilo.SerializeToString,
            naloga2__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Naloga2/GetOne',
            naloga2__pb2.Indeks.SerializeToString,
            naloga2__pb2.Stevilo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMore(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/Naloga2/SendMore',
            naloga2__pb2.Stevilo.SerializeToString,
            naloga2__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Naloga2/GetAll',
            naloga2__pb2.Empty.SerializeToString,
            naloga2__pb2.Stevilo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
