# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: naloga2.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'naloga2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnaloga2.proto\"\x07\n\x05\x45mpty\"\x1b\n\x07Stevilo\x12\x10\n\x08vrednost\x18\x01 \x01(\x02\"\x13\n\x06Indeks\x12\t\n\x01i\x18\x01 \x01(\x05\x32\x81\x01\n\x07Naloga2\x12\x1b\n\x07SendOne\x12\x08.Stevilo\x1a\x06.Empty\x12\x1b\n\x06GetOne\x12\x07.Indeks\x1a\x08.Stevilo\x12\x1e\n\x08SendMore\x12\x08.Stevilo\x1a\x06.Empty(\x01\x12\x1c\n\x06GetAll\x12\x06.Empty\x1a\x08.Stevilo0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'naloga2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=17
  _globals['_EMPTY']._serialized_end=24
  _globals['_STEVILO']._serialized_start=26
  _globals['_STEVILO']._serialized_end=53
  _globals['_INDEKS']._serialized_start=55
  _globals['_INDEKS']._serialized_end=74
  _globals['_NALOGA2']._serialized_start=77
  _globals['_NALOGA2']._serialized_end=206
# @@protoc_insertion_point(module_scope)
