# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bayes_game.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bayes_game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62\x61yes_game.proto\x12\nbayes_game\"\x12\n\x10StartGameRequest\"$\n\x11StartGameResponse\x12\x0f\n\x07game_id\x18\x01 \x01(\t\"5\n\x0cGuessRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\"^\n\rGuessResponse\x12\x11\n\tgame_over\x18\x01 \x01(\x08\x12\x10\n\x08\x61ttempts\x18\x02 \x01(\x05\x12(\n\tdirection\x18\x03 \x01(\x0e\x32\x15.bayes_game.Direction*~\n\tDirection\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05NORTH\x10\x01\x12\t\n\x05SOUTH\x10\x02\x12\x08\n\x04\x45\x41ST\x10\x03\x12\x08\n\x04WEST\x10\x04\x12\r\n\tNORTHEAST\x10\x05\x12\r\n\tSOUTHEAST\x10\x06\x12\r\n\tSOUTHWEST\x10\x07\x12\r\n\tNORTHWEST\x10\x08\x32\x97\x01\n\tBayesGame\x12H\n\tStartGame\x12\x1c.bayes_game.StartGameRequest\x1a\x1d.bayes_game.StartGameResponse\x12@\n\tMakeGuess\x12\x18.bayes_game.GuessRequest\x1a\x19.bayes_game.GuessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bayes_game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIRECTION']._serialized_start=241
  _globals['_DIRECTION']._serialized_end=367
  _globals['_STARTGAMEREQUEST']._serialized_start=32
  _globals['_STARTGAMEREQUEST']._serialized_end=50
  _globals['_STARTGAMERESPONSE']._serialized_start=52
  _globals['_STARTGAMERESPONSE']._serialized_end=88
  _globals['_GUESSREQUEST']._serialized_start=90
  _globals['_GUESSREQUEST']._serialized_end=143
  _globals['_GUESSRESPONSE']._serialized_start=145
  _globals['_GUESSRESPONSE']._serialized_end=239
  _globals['_BAYESGAME']._serialized_start=370
  _globals['_BAYESGAME']._serialized_end=521
# @@protoc_insertion_point(module_scope)
