# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: guessing_game.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'guessing_game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13guessing_game.proto\x12\rguessing_game\"#\n\x0bGameRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"3\n\x0cGuessRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\x12\r\n\x05guess\x18\x03 \x01(\x05\"u\n\nGameResult\x12\x0f\n\x07\x63orrect\x18\x01 \x01(\x08\x12\x15\n\rsecret_number\x18\x02 \x01(\x05\x12\x14\n\x0cplayer_score\x18\x03 \x01(\x05\x12\x14\n\x0cserver_score\x18\x04 \x01(\x05\x12\x13\n\x0btotal_games\x18\x05 \x01(\x05\x32\x98\x01\n\x0cGuessingGame\x12\x41\n\x08PlayGame\x12\x1a.guessing_game.GameRequest\x1a\x19.guessing_game.GameResult\x12\x45\n\x0bSubmitGuess\x12\x1b.guessing_game.GuessRequest\x1a\x19.guessing_game.GameResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guessing_game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAMEREQUEST']._serialized_start=38
  _globals['_GAMEREQUEST']._serialized_end=73
  _globals['_GUESSREQUEST']._serialized_start=75
  _globals['_GUESSREQUEST']._serialized_end=126
  _globals['_GAMERESULT']._serialized_start=128
  _globals['_GAMERESULT']._serialized_end=245
  _globals['_GUESSINGGAME']._serialized_start=248
  _globals['_GUESSINGGAME']._serialized_end=400
# @@protoc_insertion_point(module_scope)
