# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import guessing_game_pb2 as guessing__game__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in guessing_game_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GuessingGameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlayGame = channel.unary_unary(
                '/guessing_game.GuessingGame/PlayGame',
                request_serializer=guessing__game__pb2.GameRequest.SerializeToString,
                response_deserializer=guessing__game__pb2.GameResult.FromString,
                _registered_method=True)
        self.SubmitGuess = channel.unary_unary(
                '/guessing_game.GuessingGame/SubmitGuess',
                request_serializer=guessing__game__pb2.GuessRequest.SerializeToString,
                response_deserializer=guessing__game__pb2.GameResult.FromString,
                _registered_method=True)


class GuessingGameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PlayGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitGuess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GuessingGameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlayGame': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayGame,
                    request_deserializer=guessing__game__pb2.GameRequest.FromString,
                    response_serializer=guessing__game__pb2.GameResult.SerializeToString,
            ),
            'SubmitGuess': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitGuess,
                    request_deserializer=guessing__game__pb2.GuessRequest.FromString,
                    response_serializer=guessing__game__pb2.GameResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'guessing_game.GuessingGame', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('guessing_game.GuessingGame', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GuessingGame(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PlayGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/guessing_game.GuessingGame/PlayGame',
            guessing__game__pb2.GameRequest.SerializeToString,
            guessing__game__pb2.GameResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitGuess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/guessing_game.GuessingGame/SubmitGuess',
            guessing__game__pb2.GuessRequest.SerializeToString,
            guessing__game__pb2.GameResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
