# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: secure_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'secure_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14secure_service.proto\x12\x0esecure_service\" \n\rSecureRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"I\n\x0eSecureResponse\x12\r\n\x05reply\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x15\n\rauthenticated\x18\x03 \x01(\x08\x32]\n\rSecureService\x12L\n\x0bSendMessage\x12\x1d.secure_service.SecureRequest\x1a\x1e.secure_service.SecureResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secure_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SECUREREQUEST']._serialized_start=40
  _globals['_SECUREREQUEST']._serialized_end=72
  _globals['_SECURERESPONSE']._serialized_start=74
  _globals['_SECURERESPONSE']._serialized_end=147
  _globals['_SECURESERVICE']._serialized_start=149
  _globals['_SECURESERVICE']._serialized_end=242
# @@protoc_insertion_point(module_scope)
